# fly.toml
app = "zoom-r"  # или любое уникальное имя
primary_region = "ams"

[build]
  builder = "dockerfile"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true

[env]
  LOG_LEVEL = "info"
  PORT = "3000"
  